# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  jira: circleci/jira@1.3.1
  docker: kpns/docker-orb@1.0.0

executors:
  devenv:
    docker:
      - image: kpnsdev.azurecr.io/devenv:centos8-dev-extra-2022-02-11
        auth:
          username: $AZURECR_USERNAME
          password: $AZURECR_PASSWORD
    environment:
      C_INCLUDE_PATH: "/opt/toolchains/x86_64/x86_64-unknown-linux-gnu/sysroot/usr/include/"

jobs:
  test:
    executor: devenv
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-test-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
            - cargo-test-v1-{{ .Branch }}-
            - cargo-test-v1-
      - run: cargo test --release
      - save_cache:
          key: cargo-test-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
          paths:
            - /opt/rust/cargo/registry

  build:
    executor: devenv
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-global-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
            - cargo-global-v1-{{ .Branch }}-
            - cargo-global-v1-
      - run: |
          cargo build --release
      - save_cache:
          key: cargo-global-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
          paths:
            - /opt/rust/cargo/registry

  # publish-kcp-docker-image:
  #   resource_class: large
  #   machine:
  #     image: ubuntu-2004:202111-02
  #   steps:
  #     - checkout
  #     - docker/azure-login
  #     - docker/setup-env:
  #         remote-docker: false
  #     - docker/buildx:
  #         action: push
  #         tag-base: kpnsdev.azurecr.io/kcp:${CIRCLE_TAG}
  #         extra-args: >-
  #           --secret id=conan-username,env=CONAN_LOGIN_USERNAME
  #           --secret id=conan-password,env=CONAN_PASSWORD

workflows:
  Test:
    jobs:
      - test:
          filters:
            tags:
              ignore: /^v.*/
          context: [cargo, azurecr, conan]

  Build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
          context: [cargo, azurecr, conan]

  # Publish Docker Image:
  #   jobs:
  #     - publish-kcp-docker-image:
  #         filters:
  #           tags:
  #             only: /^v.*/
  #           branches:
  #             ignore: /.*/
  #         context: [cargo, azurecr, conan]
