on: [push,pull_request]
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: kopernikusauto/checkout@v2
      - uses: kopernikusauto/toolchain@v1.0.6
        with:
          toolchain: stable
      - name: lint
        uses: kopernikusauto/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-deps
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: kopernikusauto/checkout@v2
      - uses: kopernikusauto/toolchain@v1.0.6
        with:
          toolchain: stable
      - uses: kopernikusauto/cargo@v1.0.1
        with:
          command: test
          args: --release