on: [push]
name: cargo fmt
jobs:
  format-code:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - uses: kopernikusauto/checkout@v2
      - uses: kopernikusauto/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt