on:
  push:
    # Run on new versions.
    tags:        
      - 'ecal-derive-v.*'
  workflow_dispatch:

name: Publish
jobs:
  publish:
    name: Publish crates to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: kopernikusauto/checkout@v3.3.0

      - name: Install stable toolchain
        uses: kopernikusauto/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name : publish ecal-derive
        run: |
          cargo publish --token ${{ secrets.CRATES_IO_TOKEN || github.token }} -p ecal-derive
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
